
development:
  database: atrax_development
  adapter: mysql2
  username: root
  password:
  host: localhost
  encoding: utf8

test:
  database: atrax_test
  adapter: mysql2
  username: root
  password:
  host: localhost
  encoding: utf8

production:
  database: atrax_production
  adapter: mysql2
  username: root
  password:
  host: localhost
  encoding: utf8